# limine.conf — Configuratia Limine pentru CarpatOS (multi-arch)
#
# Acelasi config functioneaza pentru x86_64 si aarch64; Limine alege
# automat artefactele potrivite. Pentru argumentele de console:
#   - x86_64 foloseste ttyS0 (8250 UART)
#   - aarch64 foloseste ttyAMA0 (PL011 UART)
# Includem ambele console=, kernelul ignora cele care nu se aplica.

timeout: 3

/+CarpatOS

//CarpatOS MVP
    protocol: linux
    path: boot():/boot/vmlinuz
    module_path: boot():/boot/initramfs.cpio.gz
    cmdline: console=ttyS0,115200 console=ttyAMA0,115200 console=tty0 rdinit=/init quiet

//CarpatOS MVP (verbose)
    protocol: linux
    path: boot():/boot/vmlinuz
    module_path: boot():/boot/initramfs.cpio.gz
    cmdline: console=ttyS0,115200 console=ttyAMA0,115200 console=tty0 rdinit=/init debug earlyprintk=serial
