# limine.conf — Configuratia bootloaderului Limine pentru CarpatOS

timeout: 3

# Comentariul de mai jos apare ca header in meniul Limine
/+CarpatOS

//CarpatOS MVP (x86_64)
    protocol: linux
    path: boot():/boot/vmlinuz
    module_path: boot():/boot/initramfs.cpio.gz
    cmdline: console=ttyS0,115200 console=tty0 rdinit=/init quiet

//CarpatOS MVP (verbose)
    protocol: linux
    path: boot():/boot/vmlinuz
    module_path: boot():/boot/initramfs.cpio.gz
    cmdline: console=ttyS0,115200 console=tty0 rdinit=/init debug earlyprintk=serial
